{
 "title": "Sofar",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Current output",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sofar_logger_ActivePower_Output_Total*10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current output maximum",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sofar_logger_ActivePower_Output_Total*10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Today generation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sofar_logger_PV_Generation_Today * 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total in time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sofar_logger_PV_Generation_Total*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"sofar_logger_Fault.*\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sofar_logger_Voltage_Phase_R/10",
     "legendFormat": "Phase 1"
    },
    {
     "expr": "sofar_logger_Voltage_Phase_S/10",
     "legendFormat": "Phase 2"
    },
    {
     "expr": "sofar_logger_Voltage_Phase_T/10",
     "legendFormat": "Phase 3"
    }
   ]
  },
  {
   "title": "Output Voltage maximum",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sofar_logger_Voltage_Phase_R/10",
     "legendFormat": "Phase 1"
    },
    {
     "expr": "sofar_logger_Voltage_Phase_S/10",
     "legendFormat": "Phase 2"
    },
    {
     "expr": "sofar_logger_Voltage_Phase_T/10",
     "legendFormat": "Phase 3"
    }
   ]
  },
  {
   "title": "Current output",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sofar_logger_ActivePower_Output_Total*10",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}